#!/bin/bash

# Set to a destination folder to copy files to
DEST="${HOME}/transfers/ot"

make clean
make
[ $? -eq 0 ] && {
  [ -x trim_lslo ] && {
    echo "Trimming comments from optimized LSL script"
    ./trim_lslo
  }
}

[ "$1" == "-c" ] && {
  rm -rf ${DEST}
  mkdir -p ${DEST}

  cp Dialog_Menu.lslo ${DEST}/Dialog_Menu.lsl
  cp Online_Tracker.lslo ${DEST}/Online_Tracker.lsl
  cp *.txt *.pdf ${DEST}
}
